const chatData = [
    { keyword: "hello", response: "Hey there" },
    { keyword: "how", response: "I am a machine; I have no feelings. By the way, Haris is feeling good" },
    { keyword: "name", response: "My name is Haris Khan." },
    { keyword: "who", response: "I am a Software Engineer based in Peshawar PK." },
    { keyword: "experience", response: "I have 2+ years of experience." },
    { keyword: "projects", response: "I built more than 20 projects." },
    { keyword: "hi", response: "Hello! How's it going?" },
    { keyword: "good morning", response: "Good morning! Ready to tackle the day?" },
    { keyword: "weather", response: "The weather today is [dynamic response based on a weather API]." },
    { keyword: "news", response: "I haven't checked the news today. Anything interesting happening?" },
    { keyword: "time", response: "It's currently [dynamic response based on the current time]." },
    { keyword: "music", response: "I love music! What's your favorite genre or artist?" },
    { keyword: "movie", response: "Seen any good movies lately? I'm always looking for recommendations." },
    { keyword: "book", response: "I enjoy reading too! Any favorite books you'd recommend?" },
    { keyword: "food", response: "Hungry? What's your favorite cuisine?" },
    { keyword: "exercise", response: "Staying active is important! What's your favorite way to exercise?" },
    { keyword: "family", response: "Family is so important. How's yours doing?" },
    { keyword: "pets", response: "Pets are wonderful! Do you have any furry friends?" },
    { keyword: "travel", response: "Traveling is a great way to explore. Any favorite travel destinations?" },
    { keyword: "work", response: "How's work going for you? Busy day?" },
    { keyword: "school", response: "Education is key! What are you studying or what's your profession?" },
    { keyword: "technology", response: "Tech is fascinating! Anything in particular you find interesting?" },
    { keyword: "gaming", response: "I'm a gamer too! What games do you enjoy playing?" },
    { keyword: "weekend", response: "Looking forward to the weekend? Any plans?" },
    { keyword: "holidays", response: "Holidays are a special time. Any favorite holiday traditions?" },
    { keyword: "health", response: "Taking care of your health is important. Any health goals you're working on?" },
    { keyword: "shopping", response: "Found any great deals lately? I love a good shopping spree!" },
    { keyword: "technology", response: "Technology is ever-evolving. What's the latest tech gadget you've come across?" },
    { keyword: "dreams", response: "Dreams can be fascinating. Have any interesting dreams lately?" },
    { keyword: "goals", response: "Setting goals is essential. What goals are you currently working towards?" },
    { keyword: "hobbies", response: "Hobbies are a great way to unwind. What hobbies do you enjoy?" },
    { keyword: "inspiration", response: "Inspiration can come from anywhere. What inspires you?" },
    { keyword: "friendship", response: "Friends are like stars. How do you nurture your friendships?" },
    { keyword: "love", response: "Love is a beautiful thing. What does love mean to you?" },
    { keyword: "technology", response: "Technology is constantly evolving. Have you tried any new apps or software lately?" },
    { keyword: "podcast", response: "I love podcasts! Any favorite podcast recommendations?" },
    { keyword: "coffee", response: "Coffee or tea? What's your go-to beverage to kickstart your day?" },
    { keyword: "goals", response: "Setting goals is crucial for personal growth. What are your short-term goals?" },
    { keyword: "motivation", response: "Staying motivated can be a challenge. How do you stay motivated?" },
    { keyword: "vacation", response: "Dream vacation destination? I'd love to hear about it!" },
    { keyword: "art", response: "Art has a unique way of expressing emotions. Do you have a favorite art form or artist?" },
    { keyword: "tech gadgets", response: "The world of tech gadgets is vast. Any recent gadget that caught your eye?" },
    { keyword: "creativity", response: "Creativity knows no bounds. How do you nurture your creative side?" },
    { keyword: "goals", response: "Setting and achieving goals is a fulfilling journey. What's a recent goal you accomplished?" },
    { keyword: "celebration", response: "Life is full of reasons to celebrate. What's the last thing you celebrated?" },
    { keyword: "mindfulness", response: "Mindfulness is key to a balanced life. How do you practice mindfulness?" },
    { keyword: "learning", response: "Continuous learning is a lifelong journey. What's something new you've learned recently?" },
    { keyword: "technology", response: "The rapid pace of technological advancement is astounding. What tech trend fascinates you?" },
    { keyword: "podcast", response: "Podcasts are a great way to absorb information. Any favorite podcast episodes?" },
    { keyword: "exercise", response: "Finding the right exercise routine is crucial. What's your favorite type of workout?" },
    { keyword: "community", response: "Building a sense of community is important. How do you connect with your community?" },
    { keyword: "laughter", response: "Laughter is the best medicine. What's something that never fails to make you laugh?" },
    { keyword: "nature", response: "Nature has a calming effect. Do you have a favorite outdoor spot?" },
    { keyword: "positivity", response: "Staying positive in challenging times is admirable. How do you maintain a positive mindset?" },
    { keyword: "music", response: "Music has the power to uplift. What's a song that always boosts your mood?" },
    { keyword: "hobbies", response: "Engaging in hobbies is a great way to unwind. What hobby do you find most relaxing?" },
    { keyword: "technology", response: "Tech has transformed the way we live. How has technology positively impacted your life?" },
    { keyword: "reflection", response: "Reflection is important for personal growth. What's something you've recently reflected upon?" },
    { keyword: "gratitude", response: "Practicing gratitude can bring joy. What are you grateful for today?" },
    { keyword: "travel", response: "Traveling broadens horizons. What's a memorable travel experience you've had?" },
    { keyword: "friendship", response: "True friendships are priceless. How do you nurture your friendships?" },
    { keyword: "love", response: "Love comes in many forms. What's something you love doing in your free time?" },
    { keyword: "technology", response: "Tech trends are always changing. What's a technology you're excited about in the future?" },
    { keyword: "podcast", response: "Podcasts cover a wide range of topics. Do you prefer educational or entertaining podcasts?" },
    { keyword: "food", response: "Food brings people together. What's your favorite dish or cuisine?" },
    { keyword: "self-care", response: "Self-care is crucial for well-being. How do you practice self-care?" },
    { keyword: "motivation", response: "Motivation keeps us moving forward. What's a quote that inspires you?" },
    { keyword: "technology", response: "The tech world is dynamic. How do you stay updated on the latest tech news?" },
    { keyword: "book", response: "Books open up new worlds. Any recent book recommendations?" },
    { keyword: "goals", response: "Setting goals gives direction. What's a long-term goal you're working towards?" },
    { keyword: "mindfulness", response: "Mindfulness is about being present. How do you incorporate mindfulness into your daily routine?" },
    { keyword: "happiness", response: "Happiness is a journey. What's something that never fails to make you happy?" },
    { keyword: "creativity", response: "Creativity is a beautiful expression. How do you tap into your creative side?" },
    { keyword: "technology", response: "Technology has changed communication. What's your preferred mode of communication?" },
    { keyword: "podcast", response: "Podcasts offer diverse perspectives. Do you have a favorite genre of podcasts?" },
    { keyword: "exercise", response: "Exercise is a stress reliever. What's your favorite way to stay active?" },
    { keyword: "community", response: "Building a sense of community is important. How do you contribute to your community?" },
    { keyword: "laughter", response: "Laughter is contagious. What's a joke or funny story you recently heard?" },
    { keyword: "nature", response: "Nature is therapeutic. Do you have a favorite outdoor activity?" },
    { keyword: "positivity", response: "Positive vibes attract positive outcomes. How do you maintain a positive outlook?" },
    { keyword: "music", response: "Music is a universal language. What's a song that resonates with you on a deep level?" },
    { keyword: "hobbies", response: "Hobbies bring joy. What's a hobby you can spend hours doing?" },
  ];

  export default chatData;